/**
 * Read access to the migrated content.
 *
 * src/content/pages.json is generated by tools/scraper from the live site:
 * one entry per route, carrying the English and Dutch edition of that page.
 * This module is the only thing that touches it, and it is server-only - the
 * file is a couple of megabytes, so importing it into a client component
 * would ship the whole site's copy to the browser.
 */
import raw from "@/content/pages.json";
import type { Locale } from "./i18n";

export type Block =
  | { type: "heading"; level: number; text: string }
  | { type: "text"; text: string; html?: string }
  | { type: "list"; ordered: boolean; items: string[] }
  | { type: "quote"; text: string }
  | { type: "image"; src: string; width: number; height: number; alt: string }
  | { type: "table"; rows: string[][] }
  /** A row of figures the CMS set as heading/paragraph pairs. */
  | { type: "stats"; items: { label: string; value: string }[] }
  /**
   * A "related pages" grid, as routes rather than as copied teasers: the CMS
   * builds these out of links, and rendering the live cards keeps them in step
   * with the pages they point at instead of freezing a summary at crawl time.
   */
  | { type: "cards"; routes: string[] };

export type Edition = {
  title: string;
  /**
   * True when this edition was produced by translating the other one, because
   * the live site never published this language. Surfaced on the page: a
   * translation is not the same thing as copy the company wrote and approved.
   */
  translated?: boolean;
  description: string;
  /** Where this came from on the live site, for traceability. */
  sourcePath: string;
  published: string | null;
  /** Labels the listing pages tag this page with ("Blog", "Kennisartikel"). */
  categories: string[];
  /**
   * The picture the live index shows for this article. An article's first
   * in-body image is as often a logo or a chart as a photograph, so where the
   * index has chosen one, that is the card.
   */
  card?: { src: string; width: number; height: number };
  blocks: Block[];
};

export type PageKind =
  | "article"
  | "case"
  | "sector"
  | "service"
  | "discipline"
  | "role"
  | "page"
  | "index";

export type PageEntry = {
  route: string;
  kind: PageKind;
  en: Edition | null;
  nl: Edition | null;
};

const pages = raw as unknown as PageEntry[];

const byRoute = new Map(pages.map((page) => [page.route, page]));

/** A page plus the edition to render, and whether that is the asked-for one. */
export type ResolvedPage = {
  entry: PageEntry;
  edition: Edition;
  /**
   * Set when the requested locale has no edition of this page and the other
   * one is being shown instead. A handful of articles are published in one
   * language only on the live site.
   */
  fallbackFrom?: Locale;
};

export function resolvePage(route: string, locale: Locale): ResolvedPage | null {
  const entry = byRoute.get(route);
  if (!entry) return null;

  const wanted = entry[locale];
  if (wanted) return { entry, edition: wanted };

  const other: Locale = locale === "en" ? "nl" : "en";
  const fallback = entry[other];
  if (!fallback) return null;
  return { entry, edition: fallback, fallbackFrom: other };
}

/**
 * The designed routes - the ones with a template rather than a migrated page
 * behind them. Listed by hand because that is what they are: a decision, not
 * data, and a sitemap that silently loses one is worse than one that has to
 * be edited when a section is added.
 */
const DESIGNED_ROUTES = [
  "/",
  "/about",
  "/solutions",
  "/services",
  "/sectors",
  "/method",
  "/cases",
  "/insights",
  "/contact",
  "/sitemap",
];

/** Every route the site serves, for the sitemap. Locale-less paths. */
export function allRoutes(): { path: string; published: string | null }[] {
  const seen = new Set(DESIGNED_ROUTES);
  const out = DESIGNED_ROUTES.map((path) => ({ path, published: null as string | null }));

  for (const page of pages) {
    if (page.kind === "index" || seen.has(page.route)) continue;
    seen.add(page.route);
    out.push({
      path: page.route,
      published: page.en?.published ?? page.nl?.published ?? null,
    });
  }

  return out;
}

export function pagesOfKind(kind: PageKind): PageEntry[] {
  return pages.filter((page) => page.kind === kind);
}

/** Every route of a kind, as `generateStaticParams` wants them. */
export function slugsOfKind(kind: PageKind, prefix: string): string[] {
  return pagesOfKind(kind)
    .map((page) => page.route)
    .filter((route) => route.startsWith(`${prefix}/`))
    .map((route) => route.slice(prefix.length + 1));
}

/** First image in a page, used as the card and social image. */
export function leadImage(edition: Edition): Extract<Block, { type: "image" }> | null {
  if (edition.card) return { type: "image", ...edition.card, alt: "" };
  return (
    (edition.blocks.find((b) => b.type === "image") as
      | Extract<Block, { type: "image" }>
      | undefined) ?? null
  );
}

/** First substantial paragraph, used as a card excerpt. */
export function excerpt(edition: Edition, max = 180): string {
  if (edition.description) return truncate(edition.description, max);
  const paragraph = edition.blocks.find(
    (b) => b.type === "text" && b.text.length > 60,
  ) as Extract<Block, { type: "text" }> | undefined;
  return paragraph ? truncate(paragraph.text, max) : "";
}

function truncate(text: string, max: number): string {
  if (text.length <= max) return text;
  const cut = text.slice(0, max);
  return `${cut.slice(0, cut.lastIndexOf(" "))}...`;
}

export type CardSummary = {
  route: string;
  title: string;
  excerpt: string;
  image: Extract<Block, { type: "image" }> | null;
  published: string | null;
  categories: string[];
  /** True when only the other language's edition exists. */
  translated: boolean;
};

/** Index listing for a kind, in the given locale, newest first where dated. */
export function summaries(kind: PageKind, locale: Locale): CardSummary[] {
  return pagesOfKind(kind)
    .map((entry) => {
      const resolved = resolvePage(entry.route, locale);
      if (!resolved) return null;
      return {
        route: entry.route,
        title: resolved.edition.title,
        excerpt: excerpt(resolved.edition),
        image: leadImage(resolved.edition),
        published: resolved.edition.published,
        categories: resolved.edition.categories ?? [],
        translated: Boolean(resolved.fallbackFrom),
      } satisfies CardSummary;
    })
    .filter((card): card is CardSummary => card !== null)
    .sort((a, b) => {
      if (a.published && b.published) return b.published.localeCompare(a.published);
      if (a.published) return -1;
      if (b.published) return 1;
      return a.title.localeCompare(b.title);
    });
}

/**
 * Cards for an explicit list of routes, in the order given.
 *
 * Used by the `cards` block: the CMS decided what belongs in that grid and in
 * what order, so this keeps the order and only drops what does not resolve.
 */
export function cardsFor(routes: string[], locale: Locale): CardSummary[] {
  return routes
    .map((route) => {
      const resolved = resolvePage(route, locale);
      if (!resolved) return null;
      return {
        route,
        title: resolved.edition.title,
        excerpt: excerpt(resolved.edition, 140),
        image: leadImage(resolved.edition),
        published: resolved.edition.published,
        categories: resolved.edition.categories ?? [],
        translated: Boolean(resolved.fallbackFrom),
      } satisfies CardSummary;
    })
    .filter((card): card is CardSummary => card !== null);
}

/**
 * The one sentence on a page worth setting in the margin.
 *
 * A blockquote if the page has one; otherwise the longest thing in curly
 * quotes, which on these pages is nearly always a client or a colleague being
 * quoted inside a paragraph rather than in a quote block. Bounded at both ends
 * - under sixty characters it is a fragment, over two hundred and forty it is
 * a paragraph and stops working as a pull quote.
 */
export function pullQuote(edition: Edition): string | null {
  const block = edition.blocks.find(
    (b) => b.type === "quote" && b.text.length >= 60 && b.text.length <= 240,
  ) as Extract<Block, { type: "quote" }> | undefined;
  if (block) return block.text;

  const quoted = /“([^”]{60,240})”/;
  let best: string | null = null;
  for (const b of edition.blocks) {
    if (b.type !== "text") continue;
    const found = b.text.match(quoted);
    if (found && (!best || found[1].length > best.length)) best = found[1];
  }
  return best;
}

/** Everything under a route prefix, for "more in this section" rails. */
export function childrenOf(prefix: string, locale: Locale): CardSummary[] {
  return pages
    .filter((page) => page.route.startsWith(`${prefix}/`))
    .map((entry) => {
      const resolved = resolvePage(entry.route, locale);
      if (!resolved) return null;
      return {
        route: entry.route,
        title: resolved.edition.title,
        excerpt: excerpt(resolved.edition, 120),
        image: leadImage(resolved.edition),
        published: resolved.edition.published,
        categories: resolved.edition.categories ?? [],
        translated: Boolean(resolved.fallbackFrom),
      } satisfies CardSummary;
    })
    .filter((card): card is CardSummary => card !== null)
    .sort((a, b) => a.title.localeCompare(b.title));
}

/** Articles other than `route`, for the related-reading rail. */
export function relatedArticles(route: string, locale: Locale, count = 3): CardSummary[] {
  return summaries("article", locale)
    .filter((card) => card.route !== route)
    .slice(0, count);
}

