/**
 * Site-wide assets migrated from the live homepage: the client logo rail and
 * the testimonial cards.
 *
 * These belong to the designed sections rather than to any one migrated page,
 * so they live apart from pages.json. The file is small - a few dozen image
 * records - so unlike pages.json it is safe to import into a client
 * component, which is what the marquee and the carousel are.
 *
 * Generated by tools/scraper; do not edit by hand.
 */
import raw from "@/content/site.json";
import type { Locale } from "./i18n";

export type Media = {
  src: string;
  width: number;
  height: number;
};

export type ClientLogo = Media & {
  /** From the CMS alt text - the only place the client's name is written. */
  name: string;
};

export type Testimonial = {
  quote: string;
  name: string;
  role: string;
  portrait: Media | null;
};

type SiteAssets = {
  clients: ClientLogo[];
  testimonials: Record<Locale, Testimonial[]>;
};

const site = raw as SiteAssets;

export const clientLogos: ClientLogo[] = site.clients;

/**
 * The Dutch homepage carries fewer quotes than the English one, so a locale
 * with nothing falls back rather than rendering an empty carousel.
 */
export function testimonialsFor(locale: Locale): Testimonial[] {
  const own = site.testimonials[locale] ?? [];
  if (own.length) return own;
  const other: Locale = locale === "en" ? "nl" : "en";
  return site.testimonials[other] ?? [];
}
