import { chromium } from "playwright";
const B = "https://vedantqwe.github.io/worldemp-revamp";
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
const fails = [];
page.on("response", (r) => r.status() >= 400 && fails.push(r.status() + " " + r.url()));
await page.goto(B + "/en/solutions/finance/", { waitUntil: "networkidle" });
await page.evaluate(() => window.scrollTo(0, 340));
await page.waitForTimeout(1500);
await page.screenshot({ path: "live-1.png" });
const h = page.locator("h2").filter({ hasText: /8 roles/ }).last();
await h.scrollIntoViewIfNeeded();
await page.evaluate(() => window.scrollBy(0, -60));
await page.waitForTimeout(1600);
await page.screenshot({ path: "live-2.png" });
console.log("failed requests:", fails.length);
await browser.close();
